In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/digit_svm.csv")

In [ ]:
df

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0          1       0       0       0  ...         0         0         0         0
1          0       0       0       0  ...         0         0         0         0
2          1       0       0       0  ...         0         0         0         0
3          4       0       0       0  ...         0         0         0         0
4          0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41995      0       0       0       0  ...         0         0         0         0
41996      1       0       0       0  ...         0         0         0         0
41997      7       0       0       0  ...         0         0         0         0
41998      6       0       0       0  ...         0         0         0         0
41999      9       0       0       0  ...         0         0         0         0

[42000 rows x 785 columns]

In [ ]:
df.isnull().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [ ]:
df.isna().sum()

label       0
pixel0      0
pixel1      0
pixel2      0
pixel3      0
           ..
pixel779    0
pixel780    0
pixel781    0
pixel782    0
pixel783    0
Length: 785, dtype: int64

In [ ]:
x = df.iloc[:, 1: ].values

In [ ]:
y = df["label"].values

In [ ]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
y

array([1, 0, 1, ..., 7, 6, 9])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [ ]:
from sklearn.svm import SVC

In [ ]:
Clf = SVC(random_state = 0)

In [ ]:
Clf.fit(x_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=0, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred = Clf.predict(x_test)

In [ ]:
y_pred

array([3, 6, 9, ..., 4, 0, 5])

In [ ]:
y_test

array([3, 6, 9, ..., 4, 0, 5])

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[1000,    0,    2,    0,    2,    3,    4,    0,    4,    0],
       [   0, 1178,    5,    3,    0,    0,    1,    1,    2,    0],
       [   2,    1, 1055,    2,    1,    1,    0,    7,    8,    0],
       [   1,    2,   10, 1023,    0,   14,    2,    3,   12,    3],
       [   1,    4,    2,    0, 1004,    1,    4,    2,    0,   16],
       [   1,    0,    0,    5,    1,  913,    8,    0,    1,    1],
       [   4,    0,    0,    0,    2,    6, 1030,    0,    2,    0],
       [   1,    5,    7,    1,    8,    2,    0, 1091,    3,   11],
       [   3,    4,    3,    5,    3,    6,    3,    0,  967,    1],
       [   5,    2,    2,    4,   10,    2,    0,   14,    2,  975]])

In [ ]:
accuracy_score(y_test, y_pred)

0.9748571428571429